/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sneakers.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/sneakers.gltf");
  return (
    <group {...props} dispose={null} scale={1} position={[0, -1, .6]} rotation={[0, Math.PI / 2.5, 0]}>
      <mesh geometry={nodes.ball_1.geometry} material={materials['Material.011']} position={[0, 0.614, -3.651]} scale={0.265} />
      <mesh geometry={nodes.flexible_insert_1.geometry} material={materials['Material.002']} position={[-0.001, 0.862, 0]} rotation={[Math.PI / 2, 0, 0.003]} />
      <mesh geometry={nodes.sole_1002.geometry} material={materials['Material.001']} position={[0, 0.251, 0]} />
      <mesh geometry={nodes.sole_1003.geometry} material={materials['Material.020']} position={[0.083, 1.813, 2.614]} rotation={[0.164, 0.026, -0.034]} scale={0.824} />
      <mesh geometry={nodes.ankle_1001.geometry} material={materials['3.001']} position={[0.071, 2.122, -0.294]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ankle_1002.geometry} material={materials['Material.020']} position={[0.071, 2.122, -0.294]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
      <mesh geometry={nodes.ankle_1003.geometry} material={materials['3.001']} position={[0, 3.1, 0]} />
      <mesh geometry={nodes.ankle_1.geometry} material={materials['Material.003']} position={[0, 3.226, 0]} />
      <mesh geometry={nodes.overlays_1001.geometry} material={materials['Material.007']} position={[-0.001, 0.862, 0]} rotation={[Math.PI / 2, 0, 0.003]} />
      <mesh geometry={nodes.overlays_1006.geometry} material={materials['Material.009']} position={[0, 0.862, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.heell_patch_1002.geometry} material={materials['3.001']} position={[0.071, 2.122, -0.294]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.heell_patch_1.geometry} material={materials['Material.020']} position={[0.071, 2.085, -0.294]} rotation={[Math.PI / 2, 0, 0]} scale={0.975} />
      <mesh geometry={nodes.heell_patch_1001.geometry} material={materials['3.001']} position={[0.048, 3.021, -3.442]} rotation={[1.616, 0, 0]} />
      <mesh geometry={nodes.berets_1004.geometry} material={materials['Material.002']} position={[-1.144, 3.535, -1.378]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh geometry={nodes.berets_1005.geometry} material={materials['Material.002']} position={[1.145, 3.577, -1.394]} rotation={[0, 0.017, 0.002]} />
      <mesh geometry={nodes.berets_1002.geometry} material={materials['Material.002']} position={[0.008, 3.294, -1.85]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.berets_1001.geometry} material={materials['3.001']} position={[-0.008, 3.368, -1.544]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vamp_1.geometry} material={materials['Material.013']} position={[0.083, 1.657, 2.628]} rotation={[0.088, 0.026, -0.034]} scale={0.824} />
      <mesh geometry={nodes.vamp_1001.geometry} material={materials['Material.020']} position={[0.071, 2.122, -0.294]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.backdrop_1.geometry} material={materials['Material.004']} position={[-0.102, 0.725, -0.67]} />
      <mesh geometry={nodes.backdrop_1001.geometry} material={materials['Material.004']} position={[-0.102, 0.725, -0.67]} />
    </group>
  )
}

useGLTF.preload('/sneakers.gltf')
